# Generated by Django 4.1 on 2022-08-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('customer_birth_date', models.CharField(max_length=15)),
                ('customer_nida', models.IntegerField(unique=True, verbose_name='NO NIDA')),
            ],
        ),
    ]
