# Generated by Django 4.1 on 2022-08-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=50, unique=True)),
                ('account_desc', models.CharField(max_length=200, unique=True)),
                ('account_currency', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_birth_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('transaction_amount', models.FloatField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.customer')),
            ],
        ),
    ]
