# Generated by Django 4.1 on 2022-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_staff_staffcustomer_nextofkin_customeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_role',
            field=models.CharField(default='Normal', max_length=20, verbose_name='Normal'),
            preserve_default=False,
        ),
    ]
