# Generated by Django 4.1 on 2022-09-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0006_customer_customer_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Transfer', 'Transfer'), ('Payment', 'Payment')], max_length=20),
        ),
    ]
