# Generated by Django 4.1 on 2022-09-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0012_remove_service_service_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='CMS.customer')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='CMS.service')),
            ],
        ),
    ]
