# Generated by Django 4.1 on 2022-09-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0013_remove_service_id_alter_service_service_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextofkin',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='staffcustomer',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='staffcustomer',
            name='staff_id',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='NextOfKin',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffCustomer',
        ),
    ]
